#!/usr/bin/env bash

# Created by Matt1fy

# Loading my colors icons and defaults
source "$HOME/.config/sketchybar/mResources/mColors.sh"
source "$HOME/.config/sketchybar/mResources/mIcons.sh"
source "$HOME/.config/sketchybar/mResources/mDefaults.sh"

item_dir="$HOME/.config/sketchybar/items"
plugin_dir="$HOME/.config/sketchybar/plugins"

# COLOR PICKERS: https://felixkratz.github.io/SketchyBar/config/tricks#color-picker  OR  http://peteroupc.github.io/colorpicker/demo.html

# Menu bar config
bar_config=(
  position=top
  height=30
  y_offset=3
  border_width=4
  blur_radius=50
  color=$TRANSPARENT
  border_color=$ACCENTCOLOR
  margin=6
  corner_radius=9
  padding_left=12
  padding_right=12
  shadow=on
)

icon_defaults=(
  icon.font="$ICON_FONT"
  icon.color="$ICON_COLOR"
  icon.padding_left=3
  icon.padding_right=3
)

label_defaults=(
  label.font="$LABEL_FONT"
  label.color="$LABEL_COLOR"
  label.padding_left=2
  label.padding_right=2
)

background_defaults=(
  background.corner_radius=9
  background.height=30
  background.padding_left=5
  background.padding_right=5
)

popup_defaults=(
  popup.height=30
  popup.horizontal=false
  popup.background.border_color="$BLACK"
  popup.background.border_width=3
  popup.background.color="$BLACK"
  popup.background.corner_radius=7
  popup.background.shadow.drawing=on
)

# Render that shit
sketchybar --bar "${bar_config[@]}" \
  --default                         \
  updates=when_shown                \
  "${icon_defaults[@]}"             \
  "${label_defaults[@]}"            \
  "${background_defaults[@]}"       \
  "${popup_defaults[@]}"

# Left items
source "$item_dir/itemClock.sh"
source "$item_dir/itemStack.sh"

# Center items
source "$item_dir/itemSpaces.sh"
source "$item_dir/itemCenterdiv.sh"
source "$item_dir/itemApple.sh"
source "$item_dir/itemFrontapp.sh"

# Right items
source "$item_dir/itemBattery.sh"
source "$item_dir/itemNetwork.sh"
source "$item_dir/itemDiskmonitor.sh"
# source "$item_dir/itemAlias.sh"
source "$item_dir/itemVolume.sh"
source "$item_dir/itemSpotify.sh"

# Forcing all item scripts to run (never do this outside of sketchybarrc)
sketchybar --update

echo "sketchybar configuration loaded.."
