#!/usr/bin/env bash

# from https://github.com/FelixKratz/SketchyBar/discussions/12?sort=new#discussioncomment-1267957

function normal_mode() {
  echo "Normal Mode";

  # Colors
  . $HOME/.cache/wal/colors.sh;
  
  # Yabai
  yabai -m config active_window_border_color 0xffc46aff;
  yabai -m config normal_window_border_color 0xff928374;
  yabai -m config insert_feedback_color 0xffb16286;

  # Sketchybar
  sketchybar -m --bar color=0x732a2735
  sketchybar -m --default label.color=0xffffffff
  sketchybar -m --default icon.color=0xffffffff
  sketchybar -m --set modal icon.color=0xFF83A1F1
  sketchybar -m --set modal icon="[N]"
}

# Window Mode
function window_mode() {
  echo "Window Mode";

  # Colors
  . $HOME/.cache/wal/colors.sh;

  # Yabai
  yabai -m config active_window_border_color 0xe6e02e85;
  yabai -m config normal_window_border_color 0xe6e02e85;
  yabai -m config insert_feedback_color 0xe6e02e85;

  # Sketchybar
  sketchybar -m --bar color=0x732a2735
  sketchybar -m --default label.color=0xffffffff
  sketchybar -m --default icon.color=0xffffffff
  sketchybar -m --set modal icon.color=0xFFA8CD76
  sketchybar -m --set modal icon="[W]"
}

# Scripts Mode
function scripts_mode() {
  echo "Scripts Mode";

  # Colors
  . $HOME/.cache/wal/colors.sh;
  
  # Yabai
  yabai -m config active_window_border_color 0xff83a598;
  yabai -m config normal_window_border_color 0xff83a598;
  yabai -m config insert_feedback_color 0xff83a598;

  # Sketchybar
  sketchybar -m --bar color=0x732a2735
  sketchybar -m --default label.color=0xffffffff
  sketchybar -m --default icon.color=0xffffffff
  sketchybar -m --set modal icon.color=0xFFF29B9B
  sketchybar -m --set modal icon="[S]"
}
