#!/usr/bin/env bash

plugin_dir="~/.config/sketchybar/plugins"
config_dir="~/.config/sketchybar/configs"

# Color picker: https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=30 y_offset=3 border_width=2.5 blur_radius=100 color=0x732a2735 border_color=0xedf0c553 margin=6 corner_radius=11 padding_left=12 padding_right=12 shadow=on
           
default=(
  padding_left=5
  padding_right=5
  icon.font="Avenir Next:Heavy:16.0"
  label.font="OpenDyslexic Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=5
  icon.padding_right=5
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add item apple left \
           --set apple icon=􀣺 label.drawing=off \
           --set apple y_offset=1 \
           --set background.padding_right=5
           --set background.padding_left=2

#!/usr/bin/env sh


spaces=("main" "edit" "code" "media")
icons=("􀀜" "􀨺" "􀩼" "􁁑")
iconcolors=("0xffc46aff" "0xe6357cc3" "0xe679b9a3" "0xe615e82e" "0xe6e02e85")

SPACE_ICONS=("􀀜" "􀨺" "􀩼" "􁁑" "􀌍" "6" "7" "8" "9" "10")
SPACE_COLORS=("0xffc46aff" "0xff4b9cff" "0xe679b9a3" "0xe615e82e" "0xe6e02e85")
for i in "${!SPACE_ICONS[@]}"
 do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=3
    icon.padding_right=3
    icon.color=0xffffffff \
    icon.highlight_color="${SPACE_COLORS[i]}" \
    icon.padding_left=3 \
    icon.padding_right=3 \
    icon.background.color="${SPACE_COLORS[i]}" \
    icon.background.height=2.5 \
    icon.background.y_offset=-13 \
    background.padding_left=2 \
    background.padding_right=2 \
    label.drawing=off
    script="$plugin_dir/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

sketchybar --add bracket spaces space."$sid"
           --set         spaces background.color=0xffffffff \
                                background.corner_radius=4  \
                                background.height=20

sketchybar --add item front_app left \
           --set front_app y_offset=1 \
           --set front_app icon.drawing=off script="~/.config/sketchybar/plugins/front_app.sh" \
           --subscribe front_app front_app_switched

## Battery
# sh $config_dir/battery
sketchybar -m --add item battery right                            \
              --set battery update_freq=30                        \
              --set battery y_offset=1                            \
              script="~/.config/sketchybar/plugins/battery.sh"    \
              --subscribe battery system_woke power_source_change

sketchybar --add item clock right \
           --set clock update_freq=10 icon=􀐫  script="~/.config/sketchybar/plugins/clock.sh" \
           --set clock y_offset=1 \
           --add item volume right \
           --set volume y_offset=1 \
           --set volume script="~/.config/sketchybar/plugins/volume.sh" \
           --subscribe volume volume_change
           
##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
