#!/usr/bin/env bash

plugin_dir="~/.config/sketchybar/plugins"
config_dir="~/.config/sketchybar/configs"

# Color picker: https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar position=top height=27 y_offset=6 border_width=2.5 blur_radius=50 color=0xd9323031 border_color=0xedf0c553 margin=6 corner_radius=11 padding_left=12 padding_right=12 shadow=on
           
default=(
  padding_left=5
  padding_right=5
  icon.font="Avenir Next:Heavy:16.0"
  label.font="OpenDyslexic Nerd Font:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=5
  icon.padding_right=5
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add item apple left \
           --set apple icon=􀣺 label.drawing=off \
           --set apple y_offset=1 \
           --set background.padding_right=5
           --set background.padding_left=2

SPACE_ICONS=("1" "2" "3" "4" "5" "6" "7" "8" "9" "10")
for i in "${!SPACE_ICONS[@]}"
 do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${SPACE_ICONS[i]}"
    icon.padding_left=5
    icon.padding_right=5
    background.color=0x99f2ba2d
    background.corner_radius=5
    background.height=18
    label.drawing=off
    script="$plugin_dir/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

sketchybar --add item front_app left \
           --set front_app y_offset=1 \
           --set front_app icon.drawing=off script="~/.config/sketchybar/plugins/front_app.sh" \
           --subscribe front_app front_app_switched

## Battery
# sh $config_dir/battery
sketchybar -m --add item battery right                            \
              --set battery update_freq=30                        \
              --set battery y_offset=1                            \
              script="~/.config/sketchybar/plugins/battery.sh"    \
              --subscribe battery system_woke power_source_change

sketchybar --add item clock right \
           --set clock update_freq=10 icon=􀐫  script="~/.config/sketchybar/plugins/clock.sh" \
           --set clock y_offset=1 \
           --add item volume right \
           --set volume y_offset=1 \
           --set volume script="~/.config/sketchybar/plugins/volume.sh" \
           --subscribe volume volume_change
           
##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
