#!/usr/bin/env bash

# Created by Matt1fy

source "$HOME/.config/sketchybar/mResources/mColors.sh" # Load my defined colors

# todo make one for defined icons too

item_dir="$HOME/.config/sketchybar/items"
plugin_dir="$HOME/.config/sketchybar/plugins"
# config_dir="~/.config/sketchybar/configs"

# Color picker: https://felixkratz.github.io/SketchyBar/config/tricks#color-picker  OR  http://peteroupc.github.io/colorpicker/demo.html

# Menu Bar
sketchybar --bar position=top           \
           height=30                    \
           y_offset=3                   \
           border_width=2.5             \
           blur_radius=100              \
           color=$BAR_COLOR             \
           border_color=$ACCENTGOLDII   \
           margin=6                     \
           corner_radius=11             \
           padding_left=12              \
           padding_right=12             \
           shadow=on

# Default Properties
default=(
  padding_left=5
  padding_right=5
  icon.font="Avenir Next:Heavy:16.0"
  label.font="SF Pro:Bold:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=3
  icon.padding_right=3
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

POPUP_OFF="sketchybar --set apple.logo popup.drawing=off"
POPUP_CLICK_SCRIPT="sketchybar --set \$NAME popup.drawing=toggle"

sketchybar --add item           apple.logo left                             \
                                                                            \
           --set apple.logo     icon=􀣺                                      \
                                icon.font="SF Pro:Black:16.0"               \
                                icon.color=0xffffffff                       \
                                y_offset=1                                  \
                                background.padding_left=2                   \
                                background.padding_right=5                  \
                                label.drawing=off                           \
                                click_script="$POPUP_CLICK_SCRIPT"          \
                                popup.background.border_width=2             \
                                popup.background.corner_radius=3            \
                                popup.background.border_color=0x732a2735    \
                                                                            \
           --default background.padding_left=5                              \
                     background.padding_right=5                             \
                     icon.padding_right=5                                   \
                     icon.font="SF Pro:Bold:16.0"                           \
                     label.font="SF Pro:Semibold:13.0"                      \
                                                                            \
           --add item           apple.prefs popup.apple.logo                \
           --set apple.prefs    icon=􀍟                                     \
                                label="Preferences"                         \
                                click_script="open -a 'System Preferences';
                                              $POPUP_OFF"                   \
                                                                            \
           --add item           apple.activity popup.apple.logo             \
           --set apple.activity icon=􀟪                                     \
                                label="Activity"                            \
                                click_script="open -a 'Activity Monitor';
                                              $POPUP_OFF"                   \
                                                                            \
           --add item           apple.lock popup.apple.logo                 \
           --set apple.lock     icon=􀒳                                     \
                                label="Lock Screen"                         \
                                click_script="pmset displaysleepnow;
                                              $POPUP_OFF"

# 2nd Left Mission Control Spaces
spaces=("main" "edit" "code" "media" "misc")
space_icons=("􀀜" "􀨺" "􀊕" "􀩼" "􀌍" "6" "7" "8" "9" "10")
space_colors=("0xffc46aff" "0xff4b9cff" "0xe615e82e" "0xe679b9a3" "0xe6e02e85")
for i in "${!space_icons[@]}"
do
  sid="$(($i+1))"
  space=(
    space="$sid"
    icon="${space_icons[i]}"
    icon.padding_left=3
    icon.padding_right=3
    icon.highlight_color="${space_colors[i]}"
    icon.padding_left=3
    icon.padding_right=3
    icon.background.color="${space_colors[i]}"
    icon.background.height=2.5
    icon.background.y_offset=-20
    background.padding_left=2
    background.padding_right=2
    label.drawing=off
    script="$plugin_dir/space.sh"
    click_script="yabai -m space --focus $sid"
  )
  sketchybar --add space space."$sid" left --set space."$sid" "${space[@]}"
done

# Bracket Spaces
# sketchybar --add bracket spaces space."$sid"
#           --set         spaces background.color=0xffffffff \
#                                background.corner_radius=4  \
#                                background.height=20

# 3rd Left Focused App
sketchybar --add item front_app left \
           --set front_app icon.drawing=off script="$plugin_dir/front_app.sh" \
           --subscribe front_app front_app_switched

# 4th Center Stacks
sketchybar -m --add item stack_sep center \
              --add item stack center \
              --set stack script="$plugin_dir/stack.sh" \
              --subscribe stack window_focus front_app_switched space_change title_change \
              --set stack_sep drawing=off \
              --set stack drawing=off \
              --set stack update_freq=0
#
# 1st Right Battery
sketchybar -m --add item battery right \
              --set battery y_offset=1 \
              --set battery update_freq=60 script="$plugin_dir/battery.sh" \
              --subscribe battery system_woke power_source_change

# 2nd Right Date and Clock
sketchybar --add item clock right \
           --set clock update_freq=10 icon=􀐫  script="$plugin_dir/clock.sh" \
           --set clock y_offset=1

# 4th Right Volume
sketchybar --add item volume right \
           --set volume y_offset=1 \
           --set volume script="$plugin_dir/volume.sh" \
           --subscribe volume volume_change

# 5th Right Disk Monitor
source "$item_dir/itemDiskmonitor.sh"
# source "$item_dir/itemNetwork.sh"
source "$item_dir/spotify.sh"

sketchybar --update
